#!/bin/bash
#
# postinst script for linuxmuster-api7
# GPL v3
#

set -e

msg()
{
    message=$1
    echo
    # Bold and orange font for linuxmuster.net
    echo -e "\e[1m\e[38;5;214m$message\e[39m\e[0m"
    echo
}

case "$1" in
    install|configure)
        msg "Install Python requirements"
        /usr/bin/python3 -m pip install -r /usr/lib/python3/dist-packages/linuxmusterApi/requirements.txt

        msg "Checking config file"
        if [ ! -f "/etc/linuxmuster/api/config.yml" ] ; then
            mkdir -p /etc/linuxmuster/api
            SECRET_KEY=$(echo $(openssl rand 64) | openssl enc -A -base64)
            cat << EOF > /etc/linuxmuster/api/config.yml
uvicorn:
  port: 8001
  host: 0.0.0.0
  ssl_certfile: /etc/linuxmuster/api/lmnapi.pem
  ssl_keyfile: /etc/linuxmuster/api/lmnapi.pem
  log_level: info
secret: $SECRET_KEY
EOF
        fi
        chmod 600 /etc/linuxmuster/api/config.yml

        msg "Checking certificate"
        if [ ! -f "/etc/linuxmuster/api/lmnapi.pem" ] ; then
            /usr/lib/python3/dist-packages/linuxmusterApi/lmnapi-ssl-gen.py
        fi

        msg "Reload service linuxmuster-api"
        systemctl enable linuxmuster-api
        systemctl daemon-reload
        systemctl restart linuxmuster-api

        msg "####################################################################################
#                                                                                  #
# CAUTION: THIS PACKAGE IS NOT SECURE AND ONLY PUBLISHED FOR DEVELOPMENT PURPOSES  #
# DON'T USE IT ON A PRODUCTION SERVER!                                             #
#                                                                                  #
####################################################################################"

    ;;

    *)
    ;;

esac

exit 0
